# Generated by Django 5.2.8 on 2025-11-19 20:20

import django.db.models.deletion
import django.utils.timezone
import tcc.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaTCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PROPOSTO', 'Proposto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PROPOSTO', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim_prevista', models.DateField(blank=True, null=True, verbose_name='Data fim prevista')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_como_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_como_orientador', to=settings.AUTH_USER_MODEL, verbose_name='Orientador')),
            ],
            options={
                'verbose_name': 'Tema de TCC',
                'verbose_name_plural': 'Temas de TCC',
                'ordering': ['titulo'],
                'unique_together': {('aluno', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='entregas/', validators=[tcc.validators.validate_max_file_size, tcc.validators.validate_file_extension], verbose_name='Arquivo')),
                ('data_entrega', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da entrega')),
                ('comentario_orientador', models.TextField(blank=True, null=True, verbose_name='Comentário do orientador')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Valor entre 0 e 10.', max_digits=4, null=True, verbose_name='Nota')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tcc.tematcc', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-data_entrega'],
            },
        ),
    ]
